name: Build with Gradle using Zulu JDK 21 and upload artifacts

# 触发条件：推送代码或拉取请求时触发构建，仅针对 master 分支
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: 检出项目代码，升级到 actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: 设置 Zulu JDK 21，升级到 actions/setup-java@v4
      - name: Set up Zulu JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # Step 3: 为 gradlew 脚本添加执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: 缓存 Gradle 依赖
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: 运行 Gradle 构建，不运行测试
      - name: Build with Gradle (no tests)
        run: ./gradlew build -x test

      # Step 6: 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*.jar
